# Change these first
owner: GalaxyLittlepaws # Your GitHub organization or username, where this repository lives
repo: breedable_upptime # The name of this repository

sites:
  - name: Server Status
    url: $API_SERVER
  - name: Main Website and Portal
    url: https://galaxybreedables.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.galaxybreedables.com
  # baseUrl: /your-repo-name
  logoUrl: https://galaxybreedables.com/assets/logo-d9a3fc9f.png
  name: Status Page for Galaxy Breedables
  introTitle: "**Galaxy Breedables** is a new breedable systerm in Second Life."
  introMessage: This is a real-time status page, showing if the server or website has any problems.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
